version: '3'
services:
  kitata:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:
      - GIT_USER=AbenezerKitata
      - GIT_EMAIL=abi4kit@gmail.com
